name: kaia-eliza PROD CI pipeline
on:
  push:
    branches: ['main','feat/add-CICD']
  

jobs:
  deploy:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Get AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN_PROD }}
          role-session-name: SessionforKaiaPortal-PROD
          aws-region: ${{ secrets.AWS_REGION_PROD }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2
        id: login-ecr

      - name: Extract commit hash
        id: vars
        run: echo "::set-output name=hash::$(git rev-parse --short HEAD)"

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY_PROD }}
          IMAGE_TAG: ${{ steps.vars.outputs.hash }}
        run: |
          docker build  --build-arg VERSION=$IMAGE_TAG -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY -a