name: kaia-eliza PROD GCP CI pipeline
on:
  push:
    branches: ['main']
env:
  PROJECT_ID: "kaia-cluster-prod"
  SERVICE_ACCOUNT: "prod-kaia-eliza@kaia-cluster-prod.iam.gserviceaccount.com"
  WORKLOAD_IDENTITY_PROVIDER: "projects/380808041996/locations/global/workloadIdentityPools/kaia-cluster-prod/providers/kaia-eliza-gha-prvdr"
  AR_REPO_LOCATION: "asia-northeast3"
  AR_URL: "asia-northeast3-docker.pkg.dev/kaia-cluster-prod/kaia-eliza"  

jobs:
  deploy:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          token_format: 'access_token'
          project_id: ${{ env.PROJECT_ID }}
          service_account: ${{ env.SERVICE_ACCOUNT }}
          workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}

      - name: Docker Auth
        id: docker-auth
        uses: 'docker/login-action@v1'
        with:
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.access_token }}'
          registry: '${{ env.AR_REPO_LOCATION }}-docker.pkg.dev'

      - name: Extract commit hash
        id: vars
        run: echo "::set-output name=hash::$(git rev-parse --short HEAD)"

      - name: Build, tag, and push image to Artifact-registry
        env:
          IMAGE_TAG: ${{ steps.vars.outputs.hash }}
        run: |
          cp -r ./kaia/changes/Dockerfile ./ 
          docker build  --build-arg VERSION=$IMAGE_TAG -t ${{ env.AR_URL }}/kaia-eliza:$IMAGE_TAG .
          docker push ${{ env.AR_URL }}/kaia-eliza -a